In [3]:
import pandas as pd

In [7]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [9]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [11]:
df.isna().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [13]:
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [14]:
df.isna().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [15]:
df.columns= df.columns.str.lower()

In [30]:
df.columns=df.columns.str.replace(' ','_')
df= df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [31]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [35]:
labels=('Young','Adult','Middle Aged','Senior')
df['age_group']=pd.qcut(df['age'], q=4 , labels=labels)

In [55]:
frequency_mapping={
    'Fortnightly': 14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annualy':365,
    'Every 3 Months':90
}
df['purchase-frequency_days']= df['frequency_of_purchases'].map(frequency_mapping)

In [58]:
df[['purchase-frequency_days','frequency_of_purchases']].head()

   purchase-frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                      NaN               Annually

In [60]:
df=df.drop('promo_code_used',axis=1)

In [61]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase-frequency_days'],
      dtype='object')

In [62]:
!pip install sqlalchemy psycopg2-binary
from sqlalchemy import create_engine

Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.43)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: greenlet>=1 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 3.2 MB/s eta 0:00:01
   ----------- ---------------------------- 0.8/2.8 MB 2.4 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.8 MB 2.3 MB/s eta 0:00:01
   ---------------------- ----------------- 1.6/2.8 MB 1.9 MB/s eta 0:00:01
   -------------------------- ------------- 1.8/2.8 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.8 MB 1.6 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 1.5 MB/s  0:00:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [63]:
username="postgres"
password="krrish_23"
host="localhost"
port="5432"
database="customer_behaviour"


engine=create_engine(
    "postgresql+psycopg2://postgres:krrish_23@localhost:5432/customer_behaviour"
)

In [64]:
table_name="customer"

df.to_sql(
    table_name, engine, if_exists='replace',index=False\
)

900